"""add_daily_usage_date_index

Revision ID: a1b2c3d4e5f6
Revises: 7cc7945a6626
Create Date: 2026-04-27 11:00:00.000000

"""
from typing import Sequence, Union
from alembic import op

revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '7cc7945a6626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_daily_usage_date', 'daily_usage', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_usage_date', table_name='daily_usage')
    # ### end Alembic commands ###
