"""add_system_keys

Revision ID: ec1fd13892db
Revises: cf19980efc4e
Create Date: 2026-05-16 15:29:09.457580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1fd13892db'
down_revision: Union[str, Sequence[str], None] = 'cf19980efc4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('is_system', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('api_keys', sa.Column('use_proxy', sa.Boolean(), nullable=True, server_default='false'))
    op.execute("UPDATE api_keys SET is_system = false WHERE is_system IS NULL")
    op.execute("UPDATE api_keys SET use_proxy = false WHERE use_proxy IS NULL")
    op.alter_column('api_keys', 'is_system', nullable=False, server_default=None)
    op.alter_column('api_keys', 'use_proxy', nullable=False, server_default=None)
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('gateway_key_daily_usage_gateway_key_id_fkey'), 'gateway_key_daily_usage', type_='foreignkey')
    op.create_foreign_key(None, 'gateway_key_daily_usage', 'gateway_keys', ['gateway_key_id'], ['id'])
    op.drop_constraint(op.f('gateway_key_usage_gateway_key_id_fkey'), 'gateway_key_usage', type_='foreignkey')
    op.create_foreign_key(None, 'gateway_key_usage', 'gateway_keys', ['gateway_key_id'], ['id'])
    op.drop_constraint(op.f('uq_users_google_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_google_id'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'gateway_key_usage', type_='foreignkey')
    op.create_foreign_key(op.f('gateway_key_usage_gateway_key_id_fkey'), 'gateway_key_usage', 'gateway_keys', ['gateway_key_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'gateway_key_daily_usage', type_='foreignkey')
    op.create_foreign_key(op.f('gateway_key_daily_usage_gateway_key_id_fkey'), 'gateway_key_daily_usage', 'gateway_keys', ['gateway_key_id'], ['id'], ondelete='CASCADE')
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('api_keys', 'use_proxy')
    op.drop_column('api_keys', 'is_system')
    # ### end Alembic commands ###
