# -*- coding: utf-8 -*-

"""
Entity patterns for the PII guardrail, plus the cheap gates that keep the
scan off the hot path.

Two classes of entity:

- ``PII_PATTERNS``   — tokenized on the way up, restored on the way back.
- ``SECRET_PATTERNS``— never forwarded. A match is a hard, deterministic
  reject; there is nothing to restore because the value never leaves.

Why the gates exist
-------------------
Measured on a 588KB payload (the size ``payload_guards`` trims to), running
all patterns over every text field costs ~126ms — no single pattern is hot,
the cost is simply ``patterns x bytes`` because ``re`` walks every position.
Gating each pattern behind a literal substring test (``str.__contains__`` is
memchr-backed C) and funnelling all numeric patterns through one shared
digit-run gate brings the same scan to ~8.5ms with identical results.

The gate must be strictly *weaker* than every pattern it guards, and numeric
spans are padded before the real patterns run — with no padding the gate
silently drops matches whose pattern needs a prefix outside the digit run
(e.g. the ``+`` of ``+84 90 123 4567``): measured 84 hits instead of 105.

Secret rules are vendored from gitleaks (see ``kiro/guardrails/secret_rules.py``,
generated by ``scripts/gen_secret_rules.py``) rather than hand-rolled: a
community-maintained ruleset of 200+ formats beats us reinventing a handful.
The same "gate before you run the expensive pattern" idea applies, just with
many keywords instead of one — see ``_SECRET_KEYWORD_GATE`` below.
"""

import re

from kiro.guardrails.secret_rules import GITLEAKS_SECRET_RULES, GITLEAKS_VERSION, SecretRule

# Exposed so /health or a test can report which ruleset is live without
# reaching into the generated module directly.
SECRET_RULESET_VERSION = GITLEAKS_VERSION

# Padding applied around a digit-run gate match before the numeric patterns
# run against the span. Must cover the longest non-digit prefix any numeric
# pattern can require ("+84 " is 4). Verified lossless at >= 4.
NUMERIC_GATE_PAD = 6

# Finds runs that could hold a 9+ digit identifier. Deliberately permissive:
# separators are allowed inside so "4111 1111 1111 1111" stays one span.
DIGIT_GATE = re.compile(r"\d[\d .\-]{7,}\d")


# --- PII: tokenized and restored -------------------------------------------

# (entity_type, compiled pattern). Gated by DIGIT_GATE.
NUMERIC_PII: list[tuple[str, re.Pattern]] = [
    ("PHONE_VN", re.compile(r"(?:\+84[ .-]?|\b0)(?:\d[ .-]?){8,9}\d\b")),
    ("CCCD", re.compile(r"\b\d{12}\b")),
    ("CARD", re.compile(r"\b(?:\d[ -]?){12,18}\d\b")),
    ("IPV4", re.compile(r"\b(?:\d{1,3}\.){3}\d{1,3}\b")),
    ("IBAN", re.compile(r"\b[A-Z]{2}\d{2}[A-Z0-9]{11,30}\b")),
]

# (entity_type, required literal, compiled pattern).
LITERAL_PII: list[tuple[str, str, re.Pattern]] = [
    ("EMAIL", "@", re.compile(r"\b[\w.+-]+@[\w-]+\.[\w.-]{2,}\b")),
]


# --- Secrets: blocked, never forwarded -------------------------------------
#
# The ruleset itself (200+ SecretRule entries) is generated, not hand-written
# — see kiro/guardrails/secret_rules.py's header for the gitleaks version it
# was vendored from and how to refresh it. What lives here is:
#
#   1. one project-specific rule gitleaks cannot know about (this gateway's
#      own service-account key format);
#   2. a named exclusion list for any vendored rule that turned out to blow
#      up on this repo's own source during the false-positive regression;
#   3. the single-pass keyword gate that keeps 200+ rules affordable.

# This gateway's own service-account key (kiro/db/repositories.py
# SERVICE_ACCOUNT_KEY_PREFIX) — not a public credential format, so gitleaks
# has no rule for it and never will. Kept in the same SecretRule shape as
# the vendored rules so the engine below doesn't need two code paths.
_SERVICE_ACCOUNT_KEY_RULE = SecretRule(
    entity_type="SERVICE_ACCOUNT_KEY",
    keywords=("izisa_",),
    pattern=re.compile(r"\bizisa_[A-Za-z0-9_-]{16,}"),
    min_entropy=None,
    secret_group=0,
    allow=(),
)

# Vendored rules disabled for THIS deployment, by entity_type, with the
# measured reason each was excluded. Never edit the regex to "fix" a rule —
# that fights every future regeneration; disable it here instead, so a
# gitleaks upgrade that improves the rule automatically re-enables it only
# once removed from this set by a human who re-ran the regression.
_DISABLED_RULES: frozenset[str] = frozenset({
    # Fires on any "word-that-contains-key/token/secret/password/auth/
    # access/credential/creds = <10-150 char value>" — which is most
    # config-shaped code and docs a coding agent reads all day. Measured on
    # this repo's own source: 143 hits, essentially all env-var assignments
    # and config placeholders, none of them a real credential. Also the
    # single most expensive rule in the whole ruleset on realistic text
    # (~460ms on a 587KB git-log payload, even after keyword-windowing —
    # its own keywords are too common in ordinary code for windowing to
    # narrow anything down). Gitleaks/trufflehog users disable this rule
    # routinely for the same reason; not a quirk of this deployment.
    "GENERIC_API_KEY",
    # Keywords are the literal strings "live_" and "test_" — meant to catch
    # Lob's own key format, but "test_" alone is close to universal in a
    # test-heavy Python codebase (pytest fixtures, `test_*.py` files, `def
    # test_...`). Measured: 0 true matches, but ~30ms of regex time from
    # windows that still cover a quarter of the payload after merging.
    "LOB_API_KEY",
})

# A handful of vendored rules ship a keyword so generic (2-3 chars, a common
# substring of ordinary prose/base64/hex) that it defeats the *point* of a
# keyword gate: every occurrence still has to be windowed and (for windows
# that merge into large spans) capped, and the keyword itself dominates the
# cost of the shared gate regex just by existing as a branch. Measured on a
# 587KB git-log payload: "ey" (JWT) hit 1438 times, "s." (VAULT_SERVICE_TOKEN)
# hit 508 times — vs. single digits for every other keyword. Narrowing to a
# more specific (but still strictly-gate-compatible, i.e. never longer than
# what the rule's own pattern requires) keyword keeps both rules live without
# forcing the whole gate to pay for their worst case:
#   - JWT: real tokens base64-encode a JSON object as the first segment, and
#     '{"' always encodes to "eyJ" (3 chars) in standard base64 — the old
#     hand-written JWT pattern already relied on this same fact. "ey" alone
#     is just the base64 encoding of any byte pair starting with '{', which
#     is common in unrelated base64/hex blobs.
#   - VAULT_SERVICE_TOKEN: the rule's pattern already requires either the
#     modern "hvs.<90-120 chars>" or legacy "s.<24 chars>" prefix; keeping
#     only "hvs." in the gate means a legacy-format token would need "hvs."
#     absent and "s." present to be missed — the modern prefix is what
#     HashiCorp Vault has issued by default for years, so this is a deliberate,
#     documented recall trade-off for a 2-char keyword that otherwise cannot
#     be made more specific without exceeding what the pattern itself needs.
_KEYWORD_OVERRIDES: dict[str, tuple[str, ...]] = {
    "JWT": ("eyj",),
    "VAULT_SERVICE_TOKEN": ("hvs.",),
}


def _apply_keyword_overrides(rules: tuple[SecretRule, ...]) -> tuple[SecretRule, ...]:
    """Narrow a handful of rules' gate keywords for shared-gate performance.

    Args:
        rules: Rules straight from the vendored ruleset (plus this project's
            own), before any keyword narrowing.

    Returns:
        The same rules, with ``_KEYWORD_OVERRIDES`` entries' ``keywords``
        replaced. A rule's own ``pattern`` is untouched — only what triggers
        the cheap pre-filter changes, never what counts as a match.
    """
    out = []
    for rule in rules:
        override = _KEYWORD_OVERRIDES.get(rule.entity_type)
        out.append(rule._replace(keywords=override) if override else rule)
    return tuple(out)


LITERAL_SECRETS: tuple[SecretRule, ...] = _apply_keyword_overrides(
    tuple(rule for rule in GITLEAKS_SECRET_RULES if rule.entity_type not in _DISABLED_RULES)
    + (_SERVICE_ACCOUNT_KEY_RULE,)
)

ALL_PII_ENTITIES = frozenset(
    [e for e, _ in NUMERIC_PII] + [e for e, _, _ in LITERAL_PII]
)
ALL_SECRET_ENTITIES = frozenset(rule.entity_type for rule in LITERAL_SECRETS)

# --- Secret keyword gate -----------------------------------------------------
#
# The same idea as DIGIT_GATE, generalised to N rules: with 200+ patterns,
# testing each one's keywords against the payload separately means 200+
# passes over the text (or, worse, 200+ `text.lower()` calls). Instead this
# builds ONE alternation of every unique keyword across every rule and runs
# ONE finditer pass over ONE lowercased copy of the text, then only the
# rules whose keyword(s) actually showed up get their (comparatively
# expensive) regex run at all.
#
# Longest-keyword-first ordering is not cosmetic: Python's `re` tries
# alternatives left-to-right and stops at the first that matches, so if a
# shorter keyword is also a prefix of a longer one (e.g. a hypothetical
# "sk-ant-api03" ahead of "sk-ant-admin01" sharing "sk-ant-"), listing the
# shorter one first would make the alternation always resolve to it and
# never even attempt the longer alternative at that position — silently
# hiding whether the longer keyword is present. Longest-first guarantees
# every keyword that is truly a substring of the text gets tried and found.
_ALL_SECRET_KEYWORDS: tuple[str, ...] = tuple(sorted(
    {kw for rule in LITERAL_SECRETS for kw in rule.keywords},
    key=len, reverse=True,
))


def _trie_regex_source(words: tuple[str, ...]) -> str:
    """Build a regex source matching any of ``words``, factored as a prefix
    trie instead of a flat ``a|b|c|...`` alternation.

    Why this exists: a flat alternation of ~230 literal keywords measured at
    331ms over a 587KB payload — Python's `re` does not build a shared
    automaton for an alternation the way a real multi-pattern matcher (Aho-
    Corasick) would; it tries branches close to left-to-right at every
    position, so cost scales with branch count, not with how much of the
    text actually matches (verified: with matches held near zero, cost still
    scaled ~linearly with the number of keywords fed in, from ~0.7ms at 1
    keyword to ~57ms at 236). Collapsing shared prefixes into nesting (so
    "ghp_", "gho_", "ghs_" become "gh(?:p_|o_|s_)", and any branch that's
    down to single leaf characters becomes one ``[...]`` character class,
    which `re` *can* test in O(1)) measured at ~56ms for the same 236
    keywords — not a full fix (`re` still tries each top-level branch that
    doesn't collapse into a charset), but the best reduction found using
    only the stdlib: a hand-rolled pure-Python Aho-Corasick automaton was
    tried too and was no faster (~80ms) because a 587K-iteration Python-level
    loop has its own fixed per-character interpreter overhead, regardless of
    the matching algorithm underneath. See secret_scan_windows()'s docstring
    and the detector's performance notes for the resulting total budget.

    Args:
        words: Keywords to match, any order (this function sorts internally).

    Returns:
        A regex source string (not yet compiled) equivalent to matching any
        keyword in ``words`` as a substring.
    """

    def insert(trie: dict, word: str) -> None:
        node = trie
        for ch in word:
            node = node.setdefault(ch, {})
        node[""] = True

    def render(trie: dict) -> str:
        alternatives: list[str] = []
        single_char_leaves: list[str] = []
        optional = "" in trie
        for ch in sorted(k for k in trie if k != ""):
            sub = render(trie[ch])
            if sub == "":
                single_char_leaves.append(ch)
            else:
                alternatives.append(re.escape(ch) + sub)
        if single_char_leaves:
            alternatives.append(
                re.escape(single_char_leaves[0]) if len(single_char_leaves) == 1
                else "[" + "".join(re.escape(c) for c in single_char_leaves) + "]"
            )
        if not alternatives:
            return ""
        body = alternatives[0] if len(alternatives) == 1 else "(?:" + "|".join(alternatives) + ")"
        if not optional:
            return body
        # A bare "?" only quantifies the single regex atom right before it —
        # for a multi-character literal like "rijoi" that's just the final
        # "i", silently turning a keyword such as "eyjrijoi" (which shares
        # the prefix "eyj" with another keyword) into "eyj" + an accidentally
        # optional "i", not "eyj" optionally followed by "rijoi". Always
        # wrapping in a non-capturing group is what makes "?" apply to the
        # whole branch instead of its last character.
        return "(?:" + body + ")?"

    root: dict = {}
    for word in words:
        insert(root, word)
    return render(root)


_SECRET_KEYWORD_GATE = re.compile(_trie_regex_source(_ALL_SECRET_KEYWORDS))

# keyword -> indices into LITERAL_SECRETS of every rule that keyword gates.
# Built once so a scan only ever looks at the (usually tiny) set of rules
# whose keyword actually showed up, instead of looping all 200+ rules.
_KEYWORD_TO_RULE_INDICES: dict[str, tuple[int, ...]] = {}
for _i, _rule in enumerate(LITERAL_SECRETS):
    for _kw in _rule.keywords:
        _KEYWORD_TO_RULE_INDICES[_kw] = _KEYWORD_TO_RULE_INDICES.get(_kw, ()) + (_i,)
del _i, _rule, _kw


# Padding applied around each keyword hit before a rule's own regex runs —
# the same idea as NUMERIC_GATE_PAD, generalised per rule. Measured need:
# most gitleaks value-capture rules are shaped
# "<=50 char prefix><=20 char filler><=5 char quote><=150 char value><boundary>",
# so 300 chars on each side comfortably covers the whole capture with room
# to spare. This matters for more than correctness — without it, a keyword
# that appears constantly in ordinary text (e.g. "key", "token", "secret" in
# a payload full of commit messages and source) forces a full O(len(text))
# regex scan *per candidate rule* instead of near-instant windowed scans;
# measured on a 587KB git-log payload, that difference was the gap between a
# ~1.3s secret scan and a sub-15ms one.
_SECRET_WINDOW_PAD = 300

# Hard ceiling on how much text one rule's windows may cover in a single
# scan. A rule's keyword can itself be an ordinary substring ("test_", "s.",
# short vendor abbreviations) that shows up constantly in source code and
# commit history having nothing to do with that vendor at all; windowing
# does not help when a keyword's hits are so dense that its merged windows
# recombine into most of the payload anyway. Measured on a 587KB git-log
# payload, one such rule's windows still covered 396KB after merging and
# cost ~460ms on its own — a keyword being common is itself the signal that
# it is not doing its job as a gate, so once a rule's windows exceed this
# ceiling the excess is dropped (oldest-position-first) rather than paying
# for an effectively-full-text scan. This trades a small chance of missing
# a real secret buried in a wall of unrelated keyword noise for a bounded,
# predictable worst case — the same trade-off DIGIT_GATE and
# NUMERIC_GATE_PAD already make for PII.
_MAX_WINDOW_CHARS_PER_RULE = 50_000


def candidate_secret_rule_indices(lowered_text: str) -> set[int]:
    """Return indices into ``LITERAL_SECRETS`` worth running against ``text``.

    Args:
        lowered_text: The payload, already lower-cased by the caller — this
            is the expensive part (measured separately; see detector.py), so
            it must happen exactly once per scan rather than once per rule.

    Returns:
        Indices of rules whose keyword gate matched. Usually a handful, even
        against a large payload, because most keywords never appear at all.
    """
    indices: set[int] = set()
    for m in _SECRET_KEYWORD_GATE.finditer(lowered_text):
        indices.update(_KEYWORD_TO_RULE_INDICES.get(m.group(), ()))
    return indices


def secret_scan_windows(lowered_text: str) -> dict[int, list[tuple[int, int]]]:
    """Map each candidate rule to the merged (start, end) window(s) worth
    running its regex over, instead of the whole payload.

    A keyword can occur far more often than the credential it gates for (a
    diff full of the word "token" has one keyword hit per occurrence but at
    most a handful of real tokens, if any) — so this keeps each rule's own,
    comparatively expensive regex confined to a small span around every
    place its keyword actually showed up, merging overlapping/adjacent spans
    so a keyword that repeats every few characters still only costs one pass
    over that stretch, not one pass per occurrence.

    Args:
        lowered_text: The payload, already lower-cased once by the caller.

    Returns:
        rule index -> list of disjoint (start, end) spans, in the
        coordinates of the original (not lowered) text — lower-casing never
        changes string length in the alphabets these rules target, so the
        offsets line up directly.
    """
    raw_spans: dict[int, list[tuple[int, int]]] = {}
    n = len(lowered_text)
    for m in _SECRET_KEYWORD_GATE.finditer(lowered_text):
        idxs = _KEYWORD_TO_RULE_INDICES.get(m.group())
        if not idxs:
            continue
        lo = max(0, m.start() - _SECRET_WINDOW_PAD)
        hi = min(n, m.end() + _SECRET_WINDOW_PAD)
        for idx in idxs:
            raw_spans.setdefault(idx, []).append((lo, hi))

    merged: dict[int, list[tuple[int, int]]] = {}
    for idx, spans in raw_spans.items():
        spans.sort()
        out: list[tuple[int, int]] = [spans[0]]
        for lo, hi in spans[1:]:
            plo, phi = out[-1]
            if lo <= phi:  # overlapping or touching -> merge
                out[-1] = (plo, max(phi, hi))
            else:
                out.append((lo, hi))

        capped: list[tuple[int, int]] = []
        covered = 0
        for lo, hi in out:
            if covered >= _MAX_WINDOW_CHARS_PER_RULE:
                break
            if covered + (hi - lo) > _MAX_WINDOW_CHARS_PER_RULE:
                hi = lo + (_MAX_WINDOW_CHARS_PER_RULE - covered)
            capped.append((lo, hi))
            covered += hi - lo
        merged[idx] = capped
    return merged


def shannon_entropy(s: str) -> float:
    """Shannon entropy of ``s`` in bits/char, gitleaks' ``entropy`` gate.

    Args:
        s: The candidate secret value (the rule's ``secret_group`` capture,
            not necessarily the whole match).

    Returns:
        0.0 for an empty string, else the entropy in bits per character. A
        low-entropy "secret" (``"aaaaaaaaaaaaaaaa"``, ``"000000..."``) is
        almost always a placeholder or padding, not a real credential.
    """
    if not s:
        return 0.0
    import math
    counts: dict[str, int] = {}
    for ch in s:
        counts[ch] = counts.get(ch, 0) + 1
    length = len(s)
    return -sum((n / length) * math.log2(n / length) for n in counts.values())


# --- Validators -------------------------------------------------------------
#
# A regex match is a candidate, not a finding. Without these, a gateway that
# mostly carries source code and logs would tokenize timestamps, version
# numbers and 127.0.0.1 — degrading the prompt far more than the PII it hides.

_VN_MOBILE_PREFIX = frozenset({"3", "5", "7", "8", "9"})


def _digits(text: str) -> str:
    return "".join(c for c in text if c.isdigit())


def _luhn_ok(digits: str) -> bool:
    total, parity = 0, len(digits) % 2
    for i, ch in enumerate(digits):
        d = ord(ch) - 48
        if i % 2 == parity:
            d *= 2
            if d > 9:
                d -= 9
        total += d
    return total % 10 == 0


def _valid_phone_vn(text: str) -> bool:
    d = _digits(text)
    if d.startswith("84"):
        d = "0" + d[2:]
    # Mobile numbers are 10 digits after normalisation: 0 + prefix + 8 digits.
    return len(d) == 10 and d[0] == "0" and d[1] in _VN_MOBILE_PREFIX


def _valid_cccd(text: str) -> bool:
    d = _digits(text)
    # First three digits are the issuing province code (001-096).
    return len(d) == 12 and 1 <= int(d[:3]) <= 96


def _valid_card(text: str) -> bool:
    d = _digits(text)
    return 13 <= len(d) <= 19 and _luhn_ok(d)


def _valid_ipv4(text: str) -> bool:
    parts = text.split(".")
    if len(parts) != 4:
        return False
    try:
        octets = [int(p) for p in parts]
    except ValueError:
        return False
    if any(o > 255 for o in octets) or any(len(p) > 1 and p[0] == "0" for p in parts):
        return False
    a, b = octets[0], octets[1]
    # Loopback, private, link-local and reserved ranges are infrastructure
    # detail, not personal data — redacting them only confuses the model.
    if a in (0, 10, 127) or a >= 224:
        return False
    if a == 192 and b == 168:
        return False
    if a == 172 and 16 <= b <= 31:
        return False
    if a == 169 and b == 254:
        return False
    return True


# ISO 13616 official IBAN lengths by country code. Not exhaustive (gitleaks-
# adjacent territory keeps adding new SEPA/near-SEPA members), so an unknown
# country code only skips the length check rather than rejecting outright —
# the mod-97 checksum below still has to pass regardless.
_IBAN_LENGTH_BY_COUNTRY = {
    "AD": 24, "AE": 23, "AL": 28, "AT": 20, "AZ": 28, "BA": 20, "BE": 16,
    "BG": 22, "BH": 22, "BR": 29, "BY": 28, "CH": 21, "CR": 22, "CY": 28,
    "CZ": 24, "DE": 22, "DK": 18, "DO": 28, "EE": 20, "EG": 29, "ES": 24,
    "FI": 18, "FO": 18, "FR": 27, "GB": 22, "GE": 22, "GI": 23, "GL": 18,
    "GR": 27, "GT": 28, "HR": 21, "HU": 28, "IE": 22, "IL": 23, "IQ": 23,
    "IS": 26, "IT": 27, "JO": 30, "KW": 30, "KZ": 20, "LB": 28, "LC": 32,
    "LI": 21, "LT": 20, "LU": 20, "LV": 21, "LY": 25, "MC": 27, "MD": 24,
    "ME": 22, "MK": 19, "MR": 27, "MT": 31, "MU": 30, "NL": 18, "NO": 15,
    "PK": 24, "PL": 28, "PS": 29, "PT": 25, "QA": 29, "RO": 24, "RS": 22,
    "SA": 24, "SC": 31, "SE": 24, "SI": 19, "SK": 24, "SM": 27, "ST": 25,
    "SV": 28, "TL": 23, "TN": 24, "TR": 26, "UA": 29, "VA": 22, "VG": 24,
    "XK": 20,
}


def _valid_iban(text: str) -> bool:
    """ISO 13616 / mod-97 checksum, so a 16-digit card or other digit run
    that happens to look like ``[A-Z]{2}\\d{2}...`` doesn't get flagged as an
    IBAN, and a genuinely mistyped IBAN doesn't get tokenized as if real."""
    candidate = "".join(text.split()).upper()
    if len(candidate) < 4 or not candidate[:2].isalpha() or not candidate[2:4].isdigit():
        return False
    expected_len = _IBAN_LENGTH_BY_COUNTRY.get(candidate[:2])
    if expected_len is not None and len(candidate) != expected_len:
        return False
    # Move the 4-char country+checksum prefix to the end, then map letters to
    # numbers (A=10..Z=35) before reducing mod 97 — the ISO 13616 algorithm.
    rearranged = candidate[4:] + candidate[:4]
    if not rearranged.isalnum():
        return False
    numeric = "".join(str(int(c, 36)) for c in rearranged)
    return int(numeric) % 97 == 1


VALIDATORS = {
    "PHONE_VN": _valid_phone_vn,
    "CCCD": _valid_cccd,
    "CARD": _valid_card,
    "IPV4": _valid_ipv4,
    "IBAN": _valid_iban,
}


# --- Secret validators ------------------------------------------------------
#
# Measured against this repo, the raw patterns fire on things a coding agent
# legitimately reads: PEM headers mentioned (not embedded) in library source,
# short placeholder keys in integration docs, JWT-shaped strings built up
# from variables inside source code. Blocking on those would break the agent
# constantly, so each pattern gets a second stage that looks for evidence the
# match is a real, live credential rather than a mention of one. These run
# in addition to — never instead of — gitleaks' own entropy/allowlist gates
# on the vendored rules (see secret_rules.py's SecretRule.min_entropy/allow).
#
# Signature: (secret_value, full_text, start, end) -> bool, where
# secret_value is the rule's secret_group capture (whole match if 0), i.e.
# the credential itself with the trailing boundary/quote junk stripped.

_B64_RUN = re.compile(r"[A-Za-z0-9+/=]{40,}")

# Published example credentials that appear in vendor documentation.
_KNOWN_EXAMPLES = frozenset({
    "AKIAIOSFODNN7EXAMPLE",
    "ASIAIOSFODNN7EXAMPLE",
})


def _real_private_key(matched: str, _text: str, _start: int, _end: int) -> bool:
    """A PEM header is only a key if the captured block has real key
    material in it, not just a header/footer with prose in between.

    The vendored gitleaks pattern already requires >=64 chars between an
    opening and a matching closing marker, and captures the whole block
    (header + body + footer) as the match — so unlike the old hand-written
    pattern, there is no "text after the match" to look ahead into; the
    body is inside ``matched`` itself.
    """
    return bool(_B64_RUN.search(matched))


def _real_openai_key(matched: str, _text: str, _start: int, _end: int) -> bool:
    """Real OpenAI keys are long; doc placeholders are short stubs."""
    body = matched.split("-", 2)[-1]
    return len(body) >= 40


def _real_jwt(matched: str, _text: str, _start: int, _end: int) -> bool:
    """A JWT's first segment must decode to a JSON header declaring an alg."""
    import base64
    import json as _json

    head = matched.split(".", 1)[0]
    try:
        padded = head + "=" * (-len(head) % 4)
        claims = _json.loads(base64.urlsafe_b64decode(padded))
    except Exception:
        return False
    return isinstance(claims, dict) and "alg" in claims


def _not_a_known_example(matched: str, _text: str, _start: int, _end: int) -> bool:
    return matched not in _KNOWN_EXAMPLES


SECRET_VALIDATORS = {
    "PRIVATE_KEY": _real_private_key,
    "OPENAI_KEY": _real_openai_key,
    "JWT": _real_jwt,
    "AWS_ACCESS_KEY": _not_a_known_example,
}
