# -*- coding: utf-8 -*-

"""
GENERATED FILE — do not hand-edit.

Vendored from gitleaks v8.30.1 (config/gitleaks.toml), generated on
2026-09-18. Regenerate with::

    python3 scripts/gen_secret_rules.py

Re-check quarterly (or whenever a new gitleaks release is worth pulling in) —
see the docstring of scripts/gen_secret_rules.py for the full procedure and
this module's SKIPPED_RULES constant for the current skip list. Do not edit the rule bodies below by
hand; fix the generator or the override tables in
scripts/gen_secret_rules.py and regenerate instead, or the next regeneration
silently reverts your change.

This module is plain Python data: no network access and no TOML parsing at
import time, so it costs nothing on the request hot path.

Rules loaded: 220 / 222 from upstream. Skipped: 2
(reasons below, one per skipped rule id).

SKIPPED_RULES:
- airtable-personnal-access-token: does not compile as Python re: uses a POSIX bracket expression (e.g. [:alnum:]) that Python re mis-parses as a literal nested set, not a character class
- pkcs12-file: path-only rule (no content regex) — not applicable to text scanning
"""

import re
from typing import NamedTuple

# The pinned upstream release this file was generated from, and when. Kept
# as plain data (not just in the docstring) so a health check or test can
# report the live ruleset version without parsing this file's comments.
GITLEAKS_VERSION = 'v8.30.1'
GITLEAKS_GENERATED = '2026-09-18'


class SecretRule(NamedTuple):
    """One credential-detection rule, translated from a gitleaks TOML rule.

    Attributes:
        entity_type: Name surfaced to callers (SecretFound, logs). Stable
            across regenerations for the ids in _ENTITY_OVERRIDES so existing
            SECRET_VALIDATORS entries keep applying.
        keywords: Lowercase literal substrings; a rule is only a candidate if
            at least one of its keywords is present in the lowercased text
            (this is the single-pass gate _scan_secrets relies on).
        pattern: Compiled regex. Group 0 is the whole match; the secret value
            itself is in ``secret_group``.
        min_entropy: Minimum Shannon entropy (bits/char) the secret_group text
            must clear to count as a match, or None if the rule has no
            entropy floor. Mirrors gitleaks' `entropy` field.
        secret_group: Index of the capture group holding the credential value
            (0 = whole match, for patterns with no capture groups).
        allow: Per-rule allowlist regexes (gitleaks `[[rules.allowlists]]`).
            If any fully matches the secret_group text, the match is dropped
            — e.g. AWS's own "...EXAMPLE" doc placeholders.
    """

    entity_type: str
    keywords: tuple[str, ...]
    pattern: "re.Pattern[str]"
    min_entropy: float | None
    secret_group: int
    allow: "tuple[re.Pattern[str], ...]"


# Global gitleaks allowlist: text values these regexes fully match (template
# placeholders like "${VAR}", "%s", bare "true"/"false", example home-dir
# paths, ...) are never a real secret regardless of which rule matched them.
GITLEAKS_ALLOW_PATTERNS: "tuple[re.Pattern[str], ...]" = (
    re.compile('(?i)^true|false|null$', 34),
    re.compile('^(?i:a+|b+|c+|d+|e+|f+|g+|h+|i+|j+|k+|l+|m+|n+|o+|p+|q+|r+|s+|t+|u+|v+|w+|x+|y+|z+|\\*+|\\.+)$', 32),
    re.compile('^\\$(?:\\d+|{\\d+})$', 32),
    re.compile('^\\$(?:[A-Z_]+|[a-z_]+)$', 32),
    re.compile('^\\${(?:[A-Z_]+|[a-z_]+)}$', 32),
    re.compile('^\\{\\{[ \\t]*[\\w ().|]+[ \\t]*}}$', 32),
    re.compile('^\\$\\{\\{[ \\t]*(?:(?:env|github|secrets|vars)(?:\\.[A-Za-z]\\w+)+[\\w "\'&./=|]*)[ \\t]*}}$', 32),
    re.compile('^%(?:[A-Z_]+|[a-z_]+)%$', 32),
    re.compile('^%[+\\-# 0]?[bcdeEfFgGoOpqstTUvxX]$', 32),
    re.compile('^\\{\\d{0,2}}$', 32),
    re.compile('^@(?:[A-Z_]+|[a-z_]+)@$', 32),
    re.compile('^/Users/[a-z0-9]+/[\\w .-/]+$', 34),
    re.compile('^/(?:bin|etc|home|opt|tmp|usr|var)/[\\w ./-]+$', 32),
)

# Global gitleaks stopwords (lowercased exact values that are never a secret,
# e.g. the well-known placeholder UUID gitleaks itself ships as a fixture).
GITLEAKS_STOPWORDS: frozenset = frozenset({
    '014df517-39d1-4453-b7b3-9930c563627c',
    'abcdefghijklmnopqrstuvwxyz',
})

GITLEAKS_SECRET_RULES: tuple[SecretRule, ...] = (
    SecretRule(  # 1password-secret-key
        entity_type='1PASSWORD_SECRET_KEY',
        keywords=('a3-',),
        pattern=re.compile('\\bA3-[A-Z0-9]{6}-(?:(?:[A-Z0-9]{11})|(?:[A-Z0-9]{6}-[A-Z0-9]{5}))-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}\\b', 32),
        min_entropy=3.8,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # 1password-service-account-token
        entity_type='1PASSWORD_SERVICE_ACCOUNT_TOKEN',
        keywords=('ops_',),
        pattern=re.compile('ops_eyJ[a-zA-Z0-9+/]{250,}={0,3}', 32),
        min_entropy=4,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # adafruit-api-key
        entity_type='ADAFRUIT_API_KEY',
        keywords=('adafruit',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:adafruit)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9_-]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # adobe-client-id
        entity_type='ADOBE_CLIENT_ID',
        keywords=('adobe',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:adobe)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # adobe-client-secret
        entity_type='ADOBE_CLIENT_SECRET',
        keywords=('p8e-',),
        pattern=re.compile('\\b(p8e-[a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # age-secret-key
        entity_type='AGE_SECRET_KEY',
        keywords=('age-secret-key-1',),
        pattern=re.compile('AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}', 32),
        min_entropy=None,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # airtable-api-key
        entity_type='AIRTABLE_API_KEY',
        keywords=('airtable',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:airtable)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{17})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # algolia-api-key
        entity_type='ALGOLIA_API_KEY',
        keywords=('algolia',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:algolia)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # alibaba-access-key-id
        entity_type='ALIBABA_ACCESS_KEY_ID',
        keywords=('ltai',),
        pattern=re.compile('\\b(LTAI[a-z0-9]{20})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # alibaba-secret-key
        entity_type='ALIBABA_SECRET_KEY',
        keywords=('alibaba',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:alibaba)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{30})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # anthropic-admin-api-key
        entity_type='ANTHROPIC_ADMIN_API_KEY',
        keywords=('sk-ant-admin01',),
        pattern=re.compile('\\b(sk-ant-admin01-[a-zA-Z0-9_\\-]{93}AA)(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # anthropic-api-key
        entity_type='ANTHROPIC_KEY',
        keywords=('sk-ant-api03',),
        pattern=re.compile('\\b(sk-ant-api03-[a-zA-Z0-9_\\-]{93}AA)(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # artifactory-api-key
        entity_type='ARTIFACTORY_API_KEY',
        keywords=('akcp',),
        pattern=re.compile('\\bAKCp[A-Za-z0-9]{69}\\b', 32),
        min_entropy=4.5,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # artifactory-reference-token
        entity_type='ARTIFACTORY_REFERENCE_TOKEN',
        keywords=('cmvmd',),
        pattern=re.compile('\\bcmVmd[A-Za-z0-9]{59}\\b', 32),
        min_entropy=4.5,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # asana-client-id
        entity_type='ASANA_CLIENT_ID',
        keywords=('asana',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:asana)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # asana-client-secret
        entity_type='ASANA_CLIENT_SECRET',
        keywords=('asana',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:asana)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # atlassian-api-token
        entity_type='ATLASSIAN_API_TOKEN',
        keywords=('atatt3', 'atlassian', 'confluence', 'jira'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:(?-i:ATLASSIAN|[Aa]tlassian)|(?-i:CONFLUENCE|[Cc]onfluence)|(?-i:JIRA|[Jj]ira))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{20}[a-f0-9]{4})(?:[\\x60\'"\\s;]|\\\\[nr]|$)|\\b(ATATT3[A-Za-z0-9_\\-=]{186})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3.5,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # authress-service-client-access-key
        entity_type='AUTHRESS_SERVICE_CLIENT_ACCESS_KEY',
        keywords=('authress_', 'ext_', 'sc_', 'scauth_'),
        pattern=re.compile('\\b((?:sc|ext|scauth|authress)_[a-z0-9]{5,30}\\.[a-z0-9]{4,6}\\.(?-i:acc)[_-][a-z0-9-]{10,32}\\.[a-z0-9+/_=-]{30,120})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # aws-access-token
        entity_type='AWS_ACCESS_KEY',
        keywords=('a3t', 'abia', 'acca', 'akia', 'asia'),
        pattern=re.compile('\\b((?:A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z2-7]{16})\\b', 32),
        min_entropy=3,
        secret_group=1,
        allow=(re.compile('.+EXAMPLE$', 32),),
    ),
    SecretRule(  # aws-amazon-bedrock-api-key-long-lived
        entity_type='AWS_AMAZON_BEDROCK_API_KEY_LONG_LIVED',
        keywords=('absk',),
        pattern=re.compile('\\b(ABSK[A-Za-z0-9+/]{109,269}={0,2})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # aws-amazon-bedrock-api-key-short-lived
        entity_type='AWS_AMAZON_BEDROCK_API_KEY_SHORT_LIVED',
        keywords=('bedrock-api-key-',),
        pattern=re.compile('bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29t', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # azure-ad-client-secret
        entity_type='AZURE_AD_CLIENT_SECRET',
        keywords=('q~',),
        pattern=re.compile('(?:^|[\\\\\'"\\x60\\s>=:(,)])([a-zA-Z0-9_~.]{3}\\dQ~[a-zA-Z0-9_~.-]{31,34})(?:$|[\\\\\'"\\x60\\s<),])', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # beamer-api-token
        entity_type='BEAMER_API_TOKEN',
        keywords=('beamer',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:beamer)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(b_[a-z0-9=_\\-]{44})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # bitbucket-client-id
        entity_type='BITBUCKET_CLIENT_ID',
        keywords=('bitbucket',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:bitbucket)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # bitbucket-client-secret
        entity_type='BITBUCKET_CLIENT_SECRET',
        keywords=('bitbucket',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:bitbucket)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # bittrex-access-key
        entity_type='BITTREX_ACCESS_KEY',
        keywords=('bittrex',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:bittrex)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # bittrex-secret-key
        entity_type='BITTREX_SECRET_KEY',
        keywords=('bittrex',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:bittrex)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # cisco-meraki-api-key
        entity_type='CISCO_MERAKI_API_KEY',
        keywords=('meraki',),
        pattern=re.compile('[\\w.-]{0,50}?(?i:[\\w.-]{0,50}?(?:(?-i:[Mm]eraki|MERAKI))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # clickhouse-cloud-api-secret-key
        entity_type='CLICKHOUSE_CLOUD_API_SECRET_KEY',
        keywords=('4b1d',),
        pattern=re.compile('\\b(4b1d[A-Za-z0-9]{38})\\b', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # clojars-api-token
        entity_type='CLOJARS_API_TOKEN',
        keywords=('clojars_',),
        pattern=re.compile('(?i)CLOJARS_[a-z0-9]{60}', 34),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # cloudflare-api-key
        entity_type='CLOUDFLARE_API_KEY',
        keywords=('cloudflare',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:cloudflare)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9_-]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # cloudflare-global-api-key
        entity_type='CLOUDFLARE_GLOBAL_API_KEY',
        keywords=('cloudflare',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:cloudflare)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{37})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # cloudflare-origin-ca-key
        entity_type='CLOUDFLARE_ORIGIN_CA_KEY',
        keywords=('cloudflare', 'v1.0-'),
        pattern=re.compile('\\b(v1\\.0-[a-f0-9]{24}-[a-f0-9]{146})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # codecov-access-token
        entity_type='CODECOV_ACCESS_TOKEN',
        keywords=('codecov',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:codecov)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # cohere-api-token
        entity_type='COHERE_API_TOKEN',
        keywords=('co_api_key', 'cohere'),
        pattern=re.compile('[\\w.-]{0,50}?(?i:[\\w.-]{0,50}?(?:cohere|CO_API_KEY)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-zA-Z0-9]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=4,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # coinbase-access-token
        entity_type='COINBASE_ACCESS_TOKEN',
        keywords=('coinbase',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:coinbase)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9_-]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # confluent-access-token
        entity_type='CONFLUENT_ACCESS_TOKEN',
        keywords=('confluent',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:confluent)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # confluent-secret-key
        entity_type='CONFLUENT_SECRET_KEY',
        keywords=('confluent',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:confluent)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # contentful-delivery-api-token
        entity_type='CONTENTFUL_DELIVERY_API_TOKEN',
        keywords=('contentful',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:contentful)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{43})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # curl-auth-header
        entity_type='CURL_AUTH_HEADER',
        keywords=('curl',),
        pattern=re.compile('\\bcurl\\b(?:.*?|.*?(?:[\\r\\n]{1,2}.*?){1,5})[ \\t\\n\\r](?:-H|--header)(?:=|[ \\t]{0,5})(?:"(?:Authorization:[ \\t]{0,5}(?:Basic[ \\t]([a-z0-9+/]{8,}={0,3})|(?:Bearer|(?:Api-)?Token)[ \\t]([\\w=~@.+/-]{8,})|([\\w=~@.+/-]{8,}))|(?:(?:X-(?:[a-z]+-)?)?(?:Api-?)?(?:Key|Token)):[ \\t]{0,5}([\\w=~@.+/-]{8,}))"|\'(?:Authorization:[ \\t]{0,5}(?:Basic[ \\t]([a-z0-9+/]{8,}={0,3})|(?:Bearer|(?:Api-)?Token)[ \\t]([\\w=~@.+/-]{8,})|([\\w=~@.+/-]{8,}))|(?:(?:X-(?:[a-z]+-)?)?(?:Api-?)?(?:Key|Token)):[ \\t]{0,5}([\\w=~@.+/-]{8,}))\')(?:\\B|\\s|\\Z)', 34),
        min_entropy=2.75,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # curl-auth-user
        entity_type='CURL_AUTH_USER',
        keywords=('curl',),
        pattern=re.compile('\\bcurl\\b(?:.*|.*(?:[\\r\\n]{1,2}.*){1,5})[ \\t\\n\\r](?:-u|--user)(?:=|[ \\t]{0,5})("(:[^"]{3,}|[^:"]{3,}:|[^:"]{3,}:[^"]{3,})"|\'([^:\']{3,}:[^\']{3,})\'|((?:"[^"]{3,}"|\'[^\']{3,}\'|[\\w$@.-]+):(?:"[^"]{3,}"|\'[^\']{3,}\'|[\\w${}@.-]+)))(?:\\s|\\Z)', 32),
        min_entropy=2,
        secret_group=1,
        allow=(re.compile('[^:]+:(?:change(?:it|me)|pass(?:word)?|pwd|test|token|\\*+|x+)', 32), re.compile('[\'"]?<[^>]+>[\'"]?:[\'"]?<[^>]+>|<[^:]+:[^>]+>[\'"]?', 32), re.compile('[^:]+:\\[[^]]+]', 32), re.compile('[\'"]?[^:]+[\'"]?:[\'"]?\\$(?:\\d|\\w+|\\{(?:\\d|\\w+)})[\'"]?', 32), re.compile('\\$\\([^)]+\\):\\$\\([^)]+\\)', 32), re.compile('[\'"]?\\$?{{[^}]+}}[\'"]?:[\'"]?\\$?{{[^}]+}}[\'"]?', 32),),
    ),
    SecretRule(  # databricks-api-token
        entity_type='DATABRICKS_API_TOKEN',
        keywords=('dapi',),
        pattern=re.compile('\\b(dapi[a-f0-9]{32}(?:-\\d)?)(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # datadog-access-token
        entity_type='DATADOG_ACCESS_TOKEN',
        keywords=('datadog',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:datadog)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # defined-networking-api-token
        entity_type='DEFINED_NETWORKING_API_TOKEN',
        keywords=('dnkey',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:dnkey)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(dnkey-[a-z0-9=_\\-]{26}-[a-z0-9=_\\-]{52})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # digitalocean-access-token
        entity_type='DIGITALOCEAN_ACCESS_TOKEN',
        keywords=('doo_v1_',),
        pattern=re.compile('\\b(doo_v1_[a-f0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # digitalocean-pat
        entity_type='DIGITALOCEAN_PAT',
        keywords=('dop_v1_',),
        pattern=re.compile('\\b(dop_v1_[a-f0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # digitalocean-refresh-token
        entity_type='DIGITALOCEAN_REFRESH_TOKEN',
        keywords=('dor_v1_',),
        pattern=re.compile('(?i)\\b(dor_v1_[a-f0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # discord-api-token
        entity_type='DISCORD_API_TOKEN',
        keywords=('discord',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:discord)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # discord-client-id
        entity_type='DISCORD_CLIENT_ID',
        keywords=('discord',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:discord)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9]{18})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # discord-client-secret
        entity_type='DISCORD_CLIENT_SECRET',
        keywords=('discord',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:discord)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # doppler-api-token
        entity_type='DOPPLER_API_TOKEN',
        keywords=('dp.pt.',),
        pattern=re.compile('dp\\.pt\\.[a-z0-9]{43}', 34),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # droneci-access-token
        entity_type='DRONECI_ACCESS_TOKEN',
        keywords=('droneci',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:droneci)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # dropbox-api-token
        entity_type='DROPBOX_API_TOKEN',
        keywords=('dropbox',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{15})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # dropbox-long-lived-api-token
        entity_type='DROPBOX_LONG_LIVED_API_TOKEN',
        keywords=('dropbox',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{11}(AAAAAAAAAA)[a-z0-9\\-_=]{43})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # dropbox-short-lived-api-token
        entity_type='DROPBOX_SHORT_LIVED_API_TOKEN',
        keywords=('dropbox',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:dropbox)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(sl\\.[a-z0-9\\-=_]{135})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # duffel-api-token
        entity_type='DUFFEL_API_TOKEN',
        keywords=('duffel_',),
        pattern=re.compile('duffel_(?:test|live)_[a-z0-9_\\-=]{43}', 34),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # dynatrace-api-token
        entity_type='DYNATRACE_API_TOKEN',
        keywords=('dt0c01.',),
        pattern=re.compile('dt0c01\\.[a-z0-9]{24}\\.[a-z0-9]{64}', 34),
        min_entropy=4,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # easypost-api-token
        entity_type='EASYPOST_API_TOKEN',
        keywords=('ezak',),
        pattern=re.compile('\\bEZAK[a-z0-9]{54}\\b', 34),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # easypost-test-api-token
        entity_type='EASYPOST_TEST_API_TOKEN',
        keywords=('eztk',),
        pattern=re.compile('\\bEZTK[a-z0-9]{54}\\b', 34),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # etsy-access-token
        entity_type='ETSY_ACCESS_TOKEN',
        keywords=('etsy',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:(?-i:ETSY|[Ee]tsy))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{24})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # facebook-access-token
        entity_type='FACEBOOK_ACCESS_TOKEN',
        keywords=('facebook',),
        pattern=re.compile('(?i)\\b(\\d{15,16}(\\||%)[0-9a-z\\-_]{27,40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # facebook-page-access-token
        entity_type='FACEBOOK_PAGE_ACCESS_TOKEN',
        keywords=('eaac', 'eaam'),
        pattern=re.compile('\\b(EAA[MC][a-z0-9]{100,})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=4,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # facebook-secret
        entity_type='FACEBOOK_SECRET',
        keywords=('facebook',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:facebook)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # fastly-api-token
        entity_type='FASTLY_API_TOKEN',
        keywords=('fastly',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:fastly)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # finicity-api-token
        entity_type='FINICITY_API_TOKEN',
        keywords=('finicity',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:finicity)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # finicity-client-secret
        entity_type='FINICITY_CLIENT_SECRET',
        keywords=('finicity',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:finicity)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{20})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # finnhub-access-token
        entity_type='FINNHUB_ACCESS_TOKEN',
        keywords=('finnhub',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:finnhub)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{20})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # flickr-access-token
        entity_type='FLICKR_ACCESS_TOKEN',
        keywords=('flickr',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:flickr)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # flutterwave-encryption-key
        entity_type='FLUTTERWAVE_ENCRYPTION_KEY',
        keywords=('flwseck_test',),
        pattern=re.compile('FLWSECK_TEST-[a-h0-9]{12}', 34),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # flutterwave-public-key
        entity_type='FLUTTERWAVE_PUBLIC_KEY',
        keywords=('flwpubk_test',),
        pattern=re.compile('FLWPUBK_TEST-[a-h0-9]{32}-X', 34),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # flutterwave-secret-key
        entity_type='FLUTTERWAVE_SECRET_KEY',
        keywords=('flwseck_test',),
        pattern=re.compile('FLWSECK_TEST-[a-h0-9]{32}-X', 34),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # flyio-access-token
        entity_type='FLYIO_ACCESS_TOKEN',
        keywords=('fm1', 'fm2_', 'fo1_'),
        pattern=re.compile('\\b((?:fo1_[\\w-]{43}|fm1[ar]_[a-zA-Z0-9+\\/]{100,}={0,3}|fm2_[a-zA-Z0-9+\\/]{100,}={0,3}))(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=4,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # frameio-api-token
        entity_type='FRAMEIO_API_TOKEN',
        keywords=('fio-u-',),
        pattern=re.compile('fio-u-[a-z0-9\\-_=]{64}', 34),
        min_entropy=None,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # freemius-secret-key
        entity_type='FREEMIUS_SECRET_KEY',
        keywords=('secret_key',),
        pattern=re.compile('(?i)["\']secret_key["\']\\s*=>\\s*["\'](sk_[\\S]{29})["\']', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # freshbooks-access-token
        entity_type='FRESHBOOKS_ACCESS_TOKEN',
        keywords=('freshbooks',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:freshbooks)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # gcp-api-key
        entity_type='GCP_API_KEY',
        keywords=('aiza',),
        pattern=re.compile('\\b(AIza[\\w-]{35})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=4,
        secret_group=1,
        allow=(re.compile('AIzaSyabcdefghijklmnopqrstuvwxyz1234567', 32), re.compile('AIzaSyAnLA7NfeLquW1tJFpx_eQCxoX-oo6YyIs', 32), re.compile('AIzaSyCkEhVjf3pduRDt6d1yKOMitrUEke8agEM', 32), re.compile('AIzaSyDMAScliyLx7F0NPDEJi1QmyCgHIAODrlU', 32), re.compile('AIzaSyD3asb-2pEZVqMkmL6M9N6nHZRR_znhrh0', 32), re.compile('AIzayDNSXIbFmlXbIE6mCzDLQAqITYefhixbX4A', 32), re.compile('AIzaSyAdOS2zB6NCsk1pCdZ4-P6GBdi_UUPwX7c', 32), re.compile('AIzaSyASWm6HmTMdYWpgMnjRBjxcQ9CKctWmLd4', 32), re.compile('AIzaSyANUvH9H9BsUccjsu2pCmEkOPjjaXeDQgY', 32), re.compile('AIzaSyA5_iVawFQ8ABuTZNUdcwERLJv_a_p4wtM', 32), re.compile('AIzaSyA4UrcGxgwQFTfaI3no3t7Lt1sjmdnP5sQ', 32), re.compile('AIzaSyDSb51JiIcB6OJpwwMicseKRhhrOq1cS7g', 32), re.compile('AIzaSyBF2RrAIm4a0mO64EShQfqfd2AFnzAvvuU', 32), re.compile('AIzaSyBcE-OOIbhjyR83gm4r2MFCu4MJmprNXsw', 32), re.compile('AIzaSyB8qGxt4ec15vitgn44duC5ucxaOi4FmqE', 32), re.compile('AIzaSyA8vmApnrHNFE0bApF4hoZ11srVL_n0nvY', 32),),
    ),
    SecretRule(  # generic-api-key
        entity_type='GENERIC_API_KEY',
        keywords=('access', 'api', 'auth', 'credential', 'creds', 'key', 'passwd', 'password', 'secret', 'token'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:access|auth|(?-i:[Aa]pi|API)|credential|creds|key|passw(?:or)?d|secret|token)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([\\w.=-]{10,150}|[a-z0-9][a-z0-9+/]{11,}={0,3})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3.5,
        secret_group=1,
        allow=(re.compile('^[a-zA-Z_.-]+$', 32), re.compile('(?i)(?:access(?:ibility|or)|access[_.-]?id|random[_.-]?access|api[_.-]?(?:id|name|version)|rapid|capital|[a-z0-9-]*?api[a-z0-9-]*?:jar:|author|X-MS-Exchange-Organization-Auth|Authentication-Results|(?:credentials?[_.-]?id|withCredentials)|(?:bucket|foreign|hot|idx|natural|primary|pub(?:lic)?|schema|sequence)[_.-]?key|(?:turkey)|key[_.-]?(?:alias|board|code|frame|id|length|mesh|name|pair|press(?:ed)?|ring|selector|signature|size|stone|storetype|word|up|down|left|right)|key[_.-]?vault[_.-]?(?:id|name)|keyVaultToStoreSecrets|key(?:store|tab)[_.-]?(?:file|path)|issuerkeyhash|(?-i:[DdMm]onkey|[DM]ONKEY)|keying|(?:secret)[_.-]?(?:length|name|size)|UserSecretsId|(?:csrf)[_.-]?token|(?:io\\.jsonwebtoken[ \\t]?:[ \\t]?[\\w-]+)|(?:api|credentials|token)[_.-]?(?:endpoint|ur[il])|public[_.-]?token|(?:key|token)[_.-]?file|(?-i:(?:[A-Z_]+=\\n[A-Z_]+=|[a-z_]+=\\n[a-z_]+=)(?:\\n|\\Z))|(?-i:(?:[A-Z.]+=\\n[A-Z.]+=|[a-z.]+=\\n[a-z.]+=)(?:\\n|\\Z)))', 34), re.compile('--mount=type=secret,', 32), re.compile('import[ \\t]+{[ \\t\\w,]+}[ \\t]+from[ \\t]+[\'"][^\'"]+[\'"]', 32), re.compile('LICENSE[^=]*=\\s*"[^"]+', 32), re.compile('LIC_FILES_CHKSUM[^=]*=\\s*"[^"]+', 32), re.compile('SRC[^=]*=\\s*"[a-zA-Z0-9]+', 32),),
    ),
    SecretRule(  # github-app-token
        entity_type='GITHUB_APP_TOKEN',
        keywords=('ghs_', 'ghu_'),
        pattern=re.compile('(?:ghu|ghs)_[0-9a-zA-Z]{36}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # github-fine-grained-pat
        entity_type='GITHUB_FINE_GRAINED_PAT',
        keywords=('github_pat_',),
        pattern=re.compile('github_pat_\\w{82}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # github-oauth
        entity_type='GITHUB_OAUTH',
        keywords=('gho_',),
        pattern=re.compile('gho_[0-9a-zA-Z]{36}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # github-pat
        entity_type='GITHUB_PAT',
        keywords=('ghp_',),
        pattern=re.compile('ghp_[0-9a-zA-Z]{36}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # github-refresh-token
        entity_type='GITHUB_REFRESH_TOKEN',
        keywords=('ghr_',),
        pattern=re.compile('ghr_[0-9a-zA-Z]{36}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-cicd-job-token
        entity_type='GITLAB_CICD_JOB_TOKEN',
        keywords=('glcbt-',),
        pattern=re.compile('glcbt-[0-9a-zA-Z]{1,5}_[0-9a-zA-Z_-]{20}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-deploy-token
        entity_type='GITLAB_DEPLOY_TOKEN',
        keywords=('gldt-',),
        pattern=re.compile('gldt-[0-9a-zA-Z_\\-]{20}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-feature-flag-client-token
        entity_type='GITLAB_FEATURE_FLAG_CLIENT_TOKEN',
        keywords=('glffct-',),
        pattern=re.compile('glffct-[0-9a-zA-Z_\\-]{20}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-feed-token
        entity_type='GITLAB_FEED_TOKEN',
        keywords=('glft-',),
        pattern=re.compile('glft-[0-9a-zA-Z_\\-]{20}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-incoming-mail-token
        entity_type='GITLAB_INCOMING_MAIL_TOKEN',
        keywords=('glimt-',),
        pattern=re.compile('glimt-[0-9a-zA-Z_\\-]{25}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-kubernetes-agent-token
        entity_type='GITLAB_KUBERNETES_AGENT_TOKEN',
        keywords=('glagent-',),
        pattern=re.compile('glagent-[0-9a-zA-Z_\\-]{50}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-oauth-app-secret
        entity_type='GITLAB_OAUTH_APP_SECRET',
        keywords=('gloas-',),
        pattern=re.compile('gloas-[0-9a-zA-Z_\\-]{64}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-pat
        entity_type='GITLAB_PAT',
        keywords=('glpat-',),
        pattern=re.compile('glpat-[\\w-]{20}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-pat-routable
        entity_type='GITLAB_PAT_ROUTABLE',
        keywords=('glpat-',),
        pattern=re.compile('\\bglpat-[0-9a-zA-Z_-]{27,300}\\.[0-9a-z]{2}[0-9a-z]{7}\\b', 32),
        min_entropy=4,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-ptt
        entity_type='GITLAB_PTT',
        keywords=('glptt-',),
        pattern=re.compile('glptt-[0-9a-f]{40}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-rrt
        entity_type='GITLAB_RRT',
        keywords=('gr1348941',),
        pattern=re.compile('GR1348941[\\w-]{20}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-runner-authentication-token
        entity_type='GITLAB_RUNNER_AUTHENTICATION_TOKEN',
        keywords=('glrt-',),
        pattern=re.compile('glrt-[0-9a-zA-Z_\\-]{20}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-runner-authentication-token-routable
        entity_type='GITLAB_RUNNER_AUTHENTICATION_TOKEN_ROUTABLE',
        keywords=('glrt-',),
        pattern=re.compile('\\bglrt-t\\d_[0-9a-zA-Z_\\-]{27,300}\\.[0-9a-z]{2}[0-9a-z]{7}\\b', 32),
        min_entropy=4,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-scim-token
        entity_type='GITLAB_SCIM_TOKEN',
        keywords=('glsoat-',),
        pattern=re.compile('glsoat-[0-9a-zA-Z_\\-]{20}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitlab-session-cookie
        entity_type='GITLAB_SESSION_COOKIE',
        keywords=('_gitlab_session=',),
        pattern=re.compile('_gitlab_session=[0-9a-z]{32}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # gitter-access-token
        entity_type='GITTER_ACCESS_TOKEN',
        keywords=('gitter',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:gitter)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9_-]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # gocardless-api-token
        entity_type='GOCARDLESS_API_TOKEN',
        keywords=('gocardless', 'live_'),
        pattern=re.compile('[\\w.-]{0,50}?(?:gocardless)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(live_[a-z0-9\\-_=]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # grafana-api-key
        entity_type='GRAFANA_API_KEY',
        keywords=('eyjrijoi',),
        pattern=re.compile('(?i)\\b(eyJrIjoi[A-Za-z0-9]{70,400}={0,3})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # grafana-cloud-api-token
        entity_type='GRAFANA_CLOUD_API_TOKEN',
        keywords=('glc_',),
        pattern=re.compile('(?i)\\b(glc_[A-Za-z0-9+/]{32,400}={0,3})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # grafana-service-account-token
        entity_type='GRAFANA_SERVICE_ACCOUNT_TOKEN',
        keywords=('glsa_',),
        pattern=re.compile('(?i)\\b(glsa_[A-Za-z0-9]{32}_[A-Fa-f0-9]{8})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # harness-api-key
        entity_type='HARNESS_API_KEY',
        keywords=('pat.', 'sat.'),
        pattern=re.compile('(?:pat|sat)\\.[a-zA-Z0-9_-]{22}\\.[a-zA-Z0-9]{24}\\.[a-zA-Z0-9]{20}', 32),
        min_entropy=None,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # hashicorp-tf-api-token
        entity_type='HASHICORP_TF_API_TOKEN',
        keywords=('atlasv1',),
        pattern=re.compile('(?i)[a-z0-9]{14}\\.(?-i:atlasv1)\\.[a-z0-9\\-_=]{60,70}', 34),
        min_entropy=3.5,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # hashicorp-tf-password
        entity_type='HASHICORP_TF_PASSWORD',
        keywords=('administrator_login_password', 'password'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:administrator_login_password|password)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}("[a-z0-9=_\\-]{8,20}")(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # heroku-api-key
        entity_type='HEROKU_API_KEY',
        keywords=('heroku',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:heroku)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # heroku-api-key-v2
        entity_type='HEROKU_API_KEY_V2',
        keywords=('hrku-aa',),
        pattern=re.compile('\\b((HRKU-AA[0-9a-zA-Z_-]{58}))(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=4,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # hubspot-api-key
        entity_type='HUBSPOT_API_KEY',
        keywords=('hubspot',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:hubspot)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # huggingface-access-token
        entity_type='HUGGINGFACE_ACCESS_TOKEN',
        keywords=('hf_',),
        pattern=re.compile('\\b(hf_(?i:[a-z]{34}))(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # huggingface-organization-api-token
        entity_type='HUGGINGFACE_ORGANIZATION_API_TOKEN',
        keywords=('api_org_',),
        pattern=re.compile('\\b(api_org_(?i:[a-z]{34}))(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # infracost-api-token
        entity_type='INFRACOST_API_TOKEN',
        keywords=('ico-',),
        pattern=re.compile('\\b(ico-[a-zA-Z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # intercom-api-key
        entity_type='INTERCOM_API_KEY',
        keywords=('intercom',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:intercom)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{60})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # intra42-client-secret
        entity_type='INTRA42_CLIENT_SECRET',
        keywords=('intra', 's-s4t2af-', 's-s4t2ud-'),
        pattern=re.compile('\\b(s-s4t2(?:ud|af)-[abcdef0123456789]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # jfrog-api-key
        entity_type='JFROG_API_KEY',
        keywords=('artifactory', 'bintray', 'jfrog', 'xray'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:jfrog|artifactory|bintray|xray)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{73})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # jfrog-identity-token
        entity_type='JFROG_IDENTITY_TOKEN',
        keywords=('artifactory', 'bintray', 'jfrog', 'xray'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:jfrog|artifactory|bintray|xray)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # jwt
        entity_type='JWT',
        keywords=('ey',),
        pattern=re.compile('\\b(ey[a-zA-Z0-9]{17,}\\.ey[a-zA-Z0-9\\/\\\\_-]{17,}\\.(?:[a-zA-Z0-9\\/\\\\_-]{10,}={0,2})?)(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # jwt-base64
        entity_type='JWT_BASE64',
        keywords=('zxlk',),
        pattern=re.compile('\\bZXlK(?:(?P<alg>aGJHY2lPaU)|(?P<apu>aGNIVWlPaU)|(?P<apv>aGNIWWlPaU)|(?P<aud>aGRXUWlPaU)|(?P<b64>aU5qUWlP)|(?P<crit>amNtbDBJanBi)|(?P<cty>amRIa2lPaU)|(?P<epk>bGNHc2lPbn)|(?P<enc>bGJtTWlPaU)|(?P<jku>cWEzVWlPaU)|(?P<jwk>cWQyc2lPb)|(?P<iss>cGMzTWlPaU)|(?P<iv>cGRpSTZJ)|(?P<kid>cmFXUWlP)|(?P<key_ops>clpYbGZiM0J6SWpwY)|(?P<kty>cmRIa2lPaUp)|(?P<nonce>dWIyNWpaU0k2)|(?P<p2c>d01tTWlP)|(?P<p2s>d01uTWlPaU)|(?P<ppt>d2NIUWlPaU)|(?P<sub>emRXSWlPaU)|(?P<svt>emRuUWlP)|(?P<tag>MFlXY2lPaU)|(?P<typ>MGVYQWlPaUp)|(?P<url>MWNtd2l)|(?P<use>MWMyVWlPaUp)|(?P<ver>MlpYSWlPaU)|(?P<version>MlpYSnphVzl1SWpv)|(?P<x>NElqb2)|(?P<x5c>NE5XTWlP)|(?P<x5t>NE5YUWlPaU)|(?P<x5ts256>NE5YUWpVekkxTmlJNkl)|(?P<x5u>NE5YVWlPaU)|(?P<zip>NmFYQWlPaU))[a-zA-Z0-9\\/\\\\_+\\-\\r\\n]{40,}={0,2}', 32),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # kraken-access-token
        entity_type='KRAKEN_ACCESS_TOKEN',
        keywords=('kraken',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:kraken)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9\\/=_\\+\\-]{80,90})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # kubernetes-secret-yaml
        entity_type='KUBERNETES_SECRET_YAML',
        keywords=('secret',),
        pattern=re.compile('(?i)(?:\\bkind:[ \\t]*["\']?\\bsecret\\b["\']?(?s:.){0,200}?\\bdata:(?s:.){0,100}?\\s+([\\w.-]+:(?:[ \\t]*(?:\\||>[-+]?)\\s+)?[ \\t]*(?:["\']?[a-z0-9+/]{10,}={0,3}["\']?|\\{\\{[ \\t\\w"|$:=,.-]+}}|""|\'\'))|\\bdata:(?s:.){0,100}?\\s+([\\w.-]+:(?:[ \\t]*(?:\\||>[-+]?)\\s+)?[ \\t]*(?:["\']?[a-z0-9+/]{10,}={0,3}["\']?|\\{\\{[ \\t\\w"|$:=,.-]+}}|""|\'\'))(?s:.){0,200}?\\bkind:[ \\t]*["\']?\\bsecret\\b["\']?)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(re.compile('[\\w.-]+:(?:[ \\t]*(?:\\||>[-+]?)\\s+)?[ \\t]*(?:\\{\\{[ \\t\\w"|$:=,.-]+}}|""|\'\')', 32), re.compile('(kind:(?s:.)+\\n---\\n(?s:.)+\\bdata:|data:(?s:.)+\\n---\\n(?s:.)+\\bkind:)', 32),),
    ),
    SecretRule(  # kucoin-access-token
        entity_type='KUCOIN_ACCESS_TOKEN',
        keywords=('kucoin',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:kucoin)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{24})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # kucoin-secret-key
        entity_type='KUCOIN_SECRET_KEY',
        keywords=('kucoin',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:kucoin)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # launchdarkly-access-token
        entity_type='LAUNCHDARKLY_ACCESS_TOKEN',
        keywords=('launchdarkly',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:launchdarkly)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # linear-api-key
        entity_type='LINEAR_API_KEY',
        keywords=('lin_api_',),
        pattern=re.compile('lin_api_[a-z0-9]{40}', 34),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # linear-client-secret
        entity_type='LINEAR_CLIENT_SECRET',
        keywords=('linear',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:linear)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # linkedin-client-id
        entity_type='LINKEDIN_CLIENT_ID',
        keywords=('linked-in', 'linked_in', 'linkedin'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:linked[_-]?in)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{14})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # linkedin-client-secret
        entity_type='LINKEDIN_CLIENT_SECRET',
        keywords=('linked-in', 'linked_in', 'linkedin'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:linked[_-]?in)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # lob-api-key
        entity_type='LOB_API_KEY',
        keywords=('live_', 'test_'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:lob)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}((live|test)_[a-f0-9]{35})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # lob-pub-api-key
        entity_type='LOB_PUB_API_KEY',
        keywords=('_pub', 'live_pub', 'test_pub'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:lob)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}((test|live)_pub_[a-f0-9]{31})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # looker-client-id
        entity_type='LOOKER_CLIENT_ID',
        keywords=('looker',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:looker)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{20})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # looker-client-secret
        entity_type='LOOKER_CLIENT_SECRET',
        keywords=('looker',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:looker)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{24})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # mailchimp-api-key
        entity_type='MAILCHIMP_API_KEY',
        keywords=('mailchimp',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:MailchimpSDK.initialize|mailchimp)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{32}-us\\d\\d)(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # mailgun-private-api-token
        entity_type='MAILGUN_PRIVATE_API_TOKEN',
        keywords=('mailgun',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(key-[a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # mailgun-pub-key
        entity_type='MAILGUN_PUB_KEY',
        keywords=('mailgun',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(pubkey-[a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # mailgun-signing-key
        entity_type='MAILGUN_SIGNING_KEY',
        keywords=('mailgun',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-h0-9]{32}-[a-h0-9]{8}-[a-h0-9]{8})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # mapbox-api-token
        entity_type='MAPBOX_API_TOKEN',
        keywords=('mapbox',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:mapbox)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(pk\\.[a-z0-9]{60}\\.[a-z0-9]{22})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # mattermost-access-token
        entity_type='MATTERMOST_ACCESS_TOKEN',
        keywords=('mattermost',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:mattermost)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{26})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # maxmind-license-key
        entity_type='MAXMIND_LICENSE_KEY',
        keywords=('_mmk',),
        pattern=re.compile('\\b([A-Za-z0-9]{6}_[A-Za-z0-9]{29}_mmk)(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=4,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # messagebird-api-token
        entity_type='MESSAGEBIRD_API_TOKEN',
        keywords=('message-bird', 'message_bird', 'messagebird'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:message[_-]?bird)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{25})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # messagebird-client-id
        entity_type='MESSAGEBIRD_CLIENT_ID',
        keywords=('message-bird', 'message_bird', 'messagebird'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:message[_-]?bird)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # microsoft-teams-webhook
        entity_type='MICROSOFT_TEAMS_WEBHOOK',
        keywords=('incomingwebhook', 'webhook.office.com', 'webhookb2'),
        pattern=re.compile('https://[a-z0-9]+\\.webhook\\.office\\.com/webhookb2/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}@[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}/IncomingWebhook/[a-z0-9]{32}/[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}', 32),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # netlify-access-token
        entity_type='NETLIFY_ACCESS_TOKEN',
        keywords=('netlify',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:netlify)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{40,46})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # new-relic-browser-api-token
        entity_type='NEW_RELIC_BROWSER_API_TOKEN',
        keywords=('nrjs-',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(NRJS-[a-f0-9]{19})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # new-relic-insert-key
        entity_type='NEW_RELIC_INSERT_KEY',
        keywords=('nrii-',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(NRII-[a-z0-9-]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # new-relic-user-api-id
        entity_type='NEW_RELIC_USER_API_ID',
        keywords=('new-relic', 'new_relic', 'newrelic'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # new-relic-user-api-key
        entity_type='NEW_RELIC_USER_API_KEY',
        keywords=('nrak',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:new-relic|newrelic|new_relic)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(NRAK-[a-z0-9]{27})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # notion-api-token
        entity_type='NOTION_API_TOKEN',
        keywords=('ntn_',),
        pattern=re.compile('\\b(ntn_[0-9]{11}[A-Za-z0-9]{32}[A-Za-z0-9]{3})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=4,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # npm-access-token
        entity_type='NPM_ACCESS_TOKEN',
        keywords=('npm_',),
        pattern=re.compile('(?i)\\b(npm_[a-z0-9]{36})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # nuget-config-password
        entity_type='NUGET_CONFIG_PASSWORD',
        keywords=('<add key=',),
        pattern=re.compile('(?i)<add key=\\"(?:(?:ClearText)?Password)\\"\\s*value=\\"(.{8,})\\"\\s*/>', 34),
        min_entropy=1,
        secret_group=1,
        allow=(re.compile('33f!!lloppa', 32), re.compile('hal\\+9ooo_da!sY', 32), re.compile('^\\%\\S.*\\%$', 32),),
    ),
    SecretRule(  # nytimes-access-token
        entity_type='NYTIMES_ACCESS_TOKEN',
        keywords=('new-york-times', 'newyorktimes', 'nytimes'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:nytimes|new-york-times,|newyorktimes)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9=_\\-]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # octopus-deploy-api-key
        entity_type='OCTOPUS_DEPLOY_API_KEY',
        keywords=('api-',),
        pattern=re.compile('\\b(API-[A-Z0-9]{26})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # okta-access-token
        entity_type='OKTA_ACCESS_TOKEN',
        keywords=('okta',),
        pattern=re.compile('[\\w.-]{0,50}?(?i:[\\w.-]{0,50}?(?:(?-i:[Oo]kta|OKTA))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(00[\\w=\\-]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=4,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # openai-api-key
        entity_type='OPENAI_KEY',
        keywords=('t3blbkfj',),
        pattern=re.compile('\\b(sk-(?:proj|svcacct|admin)-(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})T3BlbkFJ(?:[A-Za-z0-9_-]{74}|[A-Za-z0-9_-]{58})\\b|sk-[a-zA-Z0-9]{20}T3BlbkFJ[a-zA-Z0-9]{20})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # openshift-user-token
        entity_type='OPENSHIFT_USER_TOKEN',
        keywords=('sha256~',),
        pattern=re.compile('\\b(sha256~[\\w-]{43})(?:[^\\w-]|\\Z)', 32),
        min_entropy=3.5,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # perplexity-api-key
        entity_type='PERPLEXITY_API_KEY',
        keywords=('pplx-',),
        pattern=re.compile('\\b(pplx-[a-zA-Z0-9]{48})(?:[\\x60\'"\\s;]|\\\\[nr]|$|\\b)', 32),
        min_entropy=4,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # plaid-api-token
        entity_type='PLAID_API_TOKEN',
        keywords=('plaid',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:plaid)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(access-(?:sandbox|development|production)-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # plaid-client-id
        entity_type='PLAID_CLIENT_ID',
        keywords=('plaid',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:plaid)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{24})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3.5,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # plaid-secret-key
        entity_type='PLAID_SECRET_KEY',
        keywords=('plaid',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:plaid)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{30})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3.5,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # planetscale-api-token
        entity_type='PLANETSCALE_API_TOKEN',
        keywords=('pscale_tkn_',),
        pattern=re.compile('\\b(pscale_tkn_[\\w=\\.-]{32,64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # planetscale-oauth-token
        entity_type='PLANETSCALE_OAUTH_TOKEN',
        keywords=('pscale_oauth_',),
        pattern=re.compile('\\b(pscale_oauth_[\\w=\\.-]{32,64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # planetscale-password
        entity_type='PLANETSCALE_PASSWORD',
        keywords=('pscale_pw_',),
        pattern=re.compile('\\b(pscale_pw_[\\w=\\.-]{32,64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # postman-api-token
        entity_type='POSTMAN_API_TOKEN',
        keywords=('pmak-',),
        pattern=re.compile('\\b(PMAK-[a-f0-9]{24}\\-[a-f0-9]{34})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # prefect-api-token
        entity_type='PREFECT_API_TOKEN',
        keywords=('pnu_',),
        pattern=re.compile('\\b(pnu_[a-zA-Z0-9]{36})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # private-key
        entity_type='PRIVATE_KEY',
        keywords=('-----begin',),
        pattern=re.compile('(?i)-----BEGIN[ A-Z0-9_-]{0,100}PRIVATE KEY(?: BLOCK)?-----[\\s\\S-]{64,}?KEY(?: BLOCK)?-----', 34),
        min_entropy=None,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # privateai-api-token
        entity_type='PRIVATEAI_API_TOKEN',
        keywords=('private-ai', 'private_ai', 'privateai'),
        pattern=re.compile('[\\w.-]{0,50}?(?i:[\\w.-]{0,50}?(?:private[_-]?ai)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # pulumi-api-token
        entity_type='PULUMI_API_TOKEN',
        keywords=('pul-',),
        pattern=re.compile('\\b(pul-[a-f0-9]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # pypi-upload-token
        entity_type='PYPI_UPLOAD_TOKEN',
        keywords=('pypi-ageichlwas5vcmc',),
        pattern=re.compile('pypi-AgEIcHlwaS5vcmc[\\w-]{50,1000}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # rapidapi-access-token
        entity_type='RAPIDAPI_ACCESS_TOKEN',
        keywords=('rapidapi',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:rapidapi)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9_-]{50})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # readme-api-token
        entity_type='README_API_TOKEN',
        keywords=('rdme_',),
        pattern=re.compile('\\b(rdme_[a-z0-9]{70})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # rubygems-api-token
        entity_type='RUBYGEMS_API_TOKEN',
        keywords=('rubygems_',),
        pattern=re.compile('\\b(rubygems_[a-f0-9]{48})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # scalingo-api-token
        entity_type='SCALINGO_API_TOKEN',
        keywords=('tk-us-',),
        pattern=re.compile('\\b(tk-us-[\\w-]{48})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # sendbird-access-id
        entity_type='SENDBIRD_ACCESS_ID',
        keywords=('sendbird',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:sendbird)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # sendbird-access-token
        entity_type='SENDBIRD_ACCESS_TOKEN',
        keywords=('sendbird',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:sendbird)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # sendgrid-api-token
        entity_type='SENDGRID_API_TOKEN',
        keywords=('sg.',),
        pattern=re.compile('\\b(SG\\.[a-z0-9=_\\-\\.]{66})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # sendinblue-api-token
        entity_type='SENDINBLUE_API_TOKEN',
        keywords=('xkeysib-',),
        pattern=re.compile('\\b(xkeysib-[a-f0-9]{64}\\-[a-z0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # sentry-access-token
        entity_type='SENTRY_ACCESS_TOKEN',
        keywords=('sentry',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:sentry)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # sentry-org-token
        entity_type='SENTRY_ORG_TOKEN',
        keywords=('sntrys_eyjpyxqio',),
        pattern=re.compile('\\bsntrys_eyJpYXQiO[a-zA-Z0-9+/]{10,200}(?:LCJyZWdpb25fdXJs|InJlZ2lvbl91cmwi|cmVnaW9uX3VybCI6)[a-zA-Z0-9+/]{10,200}={0,2}_[a-zA-Z0-9+/]{43}(?:[^a-zA-Z0-9+/]|\\Z)', 32),
        min_entropy=4.5,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # sentry-user-token
        entity_type='SENTRY_USER_TOKEN',
        keywords=('sntryu_',),
        pattern=re.compile('\\b(sntryu_[a-f0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3.5,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # settlemint-application-access-token
        entity_type='SETTLEMINT_APPLICATION_ACCESS_TOKEN',
        keywords=('sm_aat',),
        pattern=re.compile('\\b(sm_aat_[a-zA-Z0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # settlemint-personal-access-token
        entity_type='SETTLEMINT_PERSONAL_ACCESS_TOKEN',
        keywords=('sm_pat',),
        pattern=re.compile('\\b(sm_pat_[a-zA-Z0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # settlemint-service-access-token
        entity_type='SETTLEMINT_SERVICE_ACCESS_TOKEN',
        keywords=('sm_sat',),
        pattern=re.compile('\\b(sm_sat_[a-zA-Z0-9]{16})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # shippo-api-token
        entity_type='SHIPPO_API_TOKEN',
        keywords=('shippo_',),
        pattern=re.compile('\\b(shippo_(?:live|test)_[a-fA-F0-9]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # shopify-access-token
        entity_type='SHOPIFY_ACCESS_TOKEN',
        keywords=('shpat_',),
        pattern=re.compile('shpat_[a-fA-F0-9]{32}', 32),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # shopify-custom-access-token
        entity_type='SHOPIFY_CUSTOM_ACCESS_TOKEN',
        keywords=('shpca_',),
        pattern=re.compile('shpca_[a-fA-F0-9]{32}', 32),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # shopify-private-app-access-token
        entity_type='SHOPIFY_PRIVATE_APP_ACCESS_TOKEN',
        keywords=('shppa_',),
        pattern=re.compile('shppa_[a-fA-F0-9]{32}', 32),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # shopify-shared-secret
        entity_type='SHOPIFY_SHARED_SECRET',
        keywords=('shpss_',),
        pattern=re.compile('shpss_[a-fA-F0-9]{32}', 32),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # sidekiq-secret
        entity_type='SIDEKIQ_SECRET',
        keywords=('bundle_enterprise__contribsys__com', 'bundle_gems__contribsys__com'),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:BUNDLE_ENTERPRISE__CONTRIBSYS__COM|BUNDLE_GEMS__CONTRIBSYS__COM)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-f0-9]{8}:[a-f0-9]{8})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # sidekiq-sensitive-url
        entity_type='SIDEKIQ_SENSITIVE_URL',
        keywords=('enterprise.contribsys.com', 'gems.contribsys.com'),
        pattern=re.compile('(?i)\\bhttps?://([a-f0-9]{8}:[a-f0-9]{8})@(?:gems.contribsys.com|enterprise.contribsys.com)(?:[\\/|\\#|\\?|:]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # slack-app-token
        entity_type='SLACK_APP_TOKEN',
        keywords=('xapp',),
        pattern=re.compile('(?i)xapp-\\d-[A-Z0-9]+-\\d+-[a-z0-9]+', 34),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # slack-bot-token
        entity_type='SLACK_BOT_TOKEN',
        keywords=('xoxb',),
        pattern=re.compile('xoxb-[0-9]{10,13}-[0-9]{10,13}[a-zA-Z0-9-]*', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # slack-config-access-token
        entity_type='SLACK_CONFIG_ACCESS_TOKEN',
        keywords=('xoxe.xoxb-', 'xoxe.xoxp-'),
        pattern=re.compile('(?i)xoxe.xox[bp]-\\d-[A-Z0-9]{163,166}', 34),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # slack-config-refresh-token
        entity_type='SLACK_CONFIG_REFRESH_TOKEN',
        keywords=('xoxe-',),
        pattern=re.compile('(?i)xoxe-\\d-[A-Z0-9]{146}', 34),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # slack-legacy-bot-token
        entity_type='SLACK_LEGACY_BOT_TOKEN',
        keywords=('xoxb',),
        pattern=re.compile('xoxb-[0-9]{8,14}-[a-zA-Z0-9]{18,26}', 32),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # slack-legacy-token
        entity_type='SLACK_LEGACY_TOKEN',
        keywords=('xoxo', 'xoxs'),
        pattern=re.compile('xox[os]-\\d+-\\d+-\\d+-[a-fA-F\\d]+', 32),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # slack-legacy-workspace-token
        entity_type='SLACK_LEGACY_WORKSPACE_TOKEN',
        keywords=('xoxa', 'xoxr'),
        pattern=re.compile('xox[ar]-(?:\\d-)?[0-9a-zA-Z]{8,48}', 32),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # slack-user-token
        entity_type='SLACK_USER_TOKEN',
        keywords=('xoxe-', 'xoxp-'),
        pattern=re.compile('xox[pe](?:-[0-9]{10,13}){3}-[a-zA-Z0-9-]{28,34}', 32),
        min_entropy=2,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # slack-webhook-url
        entity_type='SLACK_WEBHOOK_URL',
        keywords=('hooks.slack.com',),
        pattern=re.compile('(?:https?://)?hooks.slack.com/(?:services|workflows|triggers)/[A-Za-z0-9+/]{43,56}', 32),
        min_entropy=None,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # snyk-api-token
        entity_type='SNYK_API_TOKEN',
        keywords=('snyk',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:snyk[_.-]?(?:(?:api|oauth)[_.-]?)?(?:key|token))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # sonar-api-token
        entity_type='SONAR_API_TOKEN',
        keywords=('sonar',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:sonar[_.-]?(login|token))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}((?:squ_|sqp_|sqa_)?[a-z0-9=_\\-]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=2,
        allow=(),
    ),
    SecretRule(  # sourcegraph-access-token
        entity_type='SOURCEGRAPH_ACCESS_TOKEN',
        keywords=('sgp_', 'sourcegraph'),
        pattern=re.compile('(?i)\\b(\\b(sgp_(?:[a-fA-F0-9]{16}|local)_[a-fA-F0-9]{40}|sgp_[a-fA-F0-9]{40}|[a-fA-F0-9]{40})\\b)(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # square-access-token
        entity_type='SQUARE_ACCESS_TOKEN',
        keywords=('eaaa', 'sq0atp-'),
        pattern=re.compile('\\b((?:EAAA|sq0atp-)[\\w-]{22,60})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # squarespace-access-token
        entity_type='SQUARESPACE_ACCESS_TOKEN',
        keywords=('squarespace',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:squarespace)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # stripe-access-token
        entity_type='STRIPE_ACCESS_TOKEN',
        keywords=('rk_live', 'rk_prod', 'rk_test', 'sk_live', 'sk_prod', 'sk_test'),
        pattern=re.compile('\\b((?:sk|rk)_(?:test|live|prod)_[a-zA-Z0-9]{10,99})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=2,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # sumologic-access-id
        entity_type='SUMOLOGIC_ACCESS_ID',
        keywords=('sumo',),
        pattern=re.compile('[\\w.-]{0,50}?(?i:[\\w.-]{0,50}?(?:(?-i:[Ss]umo|SUMO))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3})(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(su[a-zA-Z0-9]{12})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # sumologic-access-token
        entity_type='SUMOLOGIC_ACCESS_TOKEN',
        keywords=('sumo',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:(?-i:[Ss]umo|SUMO))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{64})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=3,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # telegram-bot-api-token
        entity_type='TELEGRAM_BOT_API_TOKEN',
        keywords=('telegr',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:telegr)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9]{5,16}:(?-i:A)[a-z0-9_\\-]{34})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # travisci-access-token
        entity_type='TRAVISCI_ACCESS_TOKEN',
        keywords=('travis',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:travis)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{22})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # twilio-api-key
        entity_type='TWILIO_API_KEY',
        keywords=('sk',),
        pattern=re.compile('SK[0-9a-fA-F]{32}', 32),
        min_entropy=3,
        secret_group=0,
        allow=(),
    ),
    SecretRule(  # twitch-api-token
        entity_type='TWITCH_API_TOKEN',
        keywords=('twitch',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:twitch)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{30})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # twitter-access-secret
        entity_type='TWITTER_ACCESS_SECRET',
        keywords=('twitter',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{45})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # twitter-access-token
        entity_type='TWITTER_ACCESS_TOKEN',
        keywords=('twitter',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([0-9]{15,25}-[a-zA-Z0-9]{20,40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # twitter-api-key
        entity_type='TWITTER_API_KEY',
        keywords=('twitter',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{25})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # twitter-api-secret
        entity_type='TWITTER_API_SECRET',
        keywords=('twitter',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{50})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # twitter-bearer-token
        entity_type='TWITTER_BEARER_TOKEN',
        keywords=('twitter',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:twitter)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(A{22}[a-zA-Z0-9%]{80,100})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # typeform-api-token
        entity_type='TYPEFORM_API_TOKEN',
        keywords=('tfp_',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:typeform)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(tfp_[a-z0-9\\-_\\.=]{59})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # vault-batch-token
        entity_type='VAULT_BATCH_TOKEN',
        keywords=('hvb.',),
        pattern=re.compile('\\b(hvb\\.[\\w-]{138,300})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=4,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # vault-service-token
        entity_type='VAULT_SERVICE_TOKEN',
        keywords=('hvs.', 's.'),
        pattern=re.compile('\\b((?:hvs\\.[\\w-]{90,120}|s\\.(?i:[a-z0-9]{24})))(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 32),
        min_entropy=3.5,
        secret_group=1,
        allow=(re.compile('s\\.[A-Za-z]{24}', 32),),
    ),
    SecretRule(  # yandex-access-token
        entity_type='YANDEX_ACCESS_TOKEN',
        keywords=('yandex',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:yandex)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(t1\\.[A-Z0-9a-z_-]+[=]{0,2}\\.[A-Z0-9a-z_-]{86}[=]{0,2})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # yandex-api-key
        entity_type='YANDEX_API_KEY',
        keywords=('yandex',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:yandex)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(AQVN[A-Za-z0-9_\\-]{35,38})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # yandex-aws-access-token
        entity_type='YANDEX_AWS_ACCESS_TOKEN',
        keywords=('yandex',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:yandex)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(YC[a-zA-Z0-9_\\-]{38})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
    SecretRule(  # zendesk-secret-key
        entity_type='ZENDESK_SECRET_KEY',
        keywords=('zendesk',),
        pattern=re.compile('(?i)[\\w.-]{0,50}?(?:zendesk)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-z0-9]{40})(?:[\\x60\'"\\s;]|\\\\[nr]|$)', 34),
        min_entropy=None,
        secret_group=1,
        allow=(),
    ),
)

SKIPPED_RULES: tuple[tuple[str, str], ...] = (
    ('airtable-personnal-access-token', 'does not compile as Python re: uses a POSIX bracket expression (e.g. [:alnum:]) that Python re mis-parses as a literal nested set, not a character class'),
    ('pkcs12-file', 'path-only rule (no content regex) — not applicable to text scanning'),
)
